# Generated by Django 3.0.2 on 2020-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abrev',
            field=models.CharField(max_length=10, null=True, verbose_name='School Abbreviation'),
        ),
        migrations.AddField(
            model_name='team',
            name='abrev',
            field=models.CharField(max_length=10, null=True, verbose_name='School Abbreviation'),
        ),
    ]
