# Generated by Django 2.2.5 on 2020-01-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0002_auto_20200111_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cfb.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(default=1, max_length=10, verbose_name='Team Type'),
            preserve_default=False,
        ),
    ]
