# Generated by Django 2.2.5 on 2020-01-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0003_auto_20200112_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfb.Coach')),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfb.Conference')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.Team')),
            ],
            options={
                'unique_together': {('team', 'season')},
            },
        ),
    ]
