# Generated by Django 2.2.5 on 2020-01-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0004_teamseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.FloatField(null=True, verbose_name='Base Salary')),
                ('total', models.FloatField(null=True, verbose_name='Total Salary')),
                ('bonus', models.FloatField(null=True, verbose_name='Bonus')),
                ('buyout', models.FloatField(null=True, verbose_name='Buyout')),
                ('teamseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.TeamSeason')),
            ],
        ),
        migrations.CreateModel(
            name='CfbstatsUrlId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlId', models.CharField(max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.Team')),
            ],
        ),
    ]
