# Generated by Django 2.2.5 on 2020-01-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0005_cfbstatsurlid_coachpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachpay',
            name='bonusPaid',
            field=models.FloatField(null=True, verbose_name='Bonus Paid'),
        ),
    ]
