# Generated by Django 2.2.5 on 2020-01-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0006_coachpay_bonuspaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Description')),
                ('win', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cfbstatsurlid',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfbs', to='cfb.Team'),
        ),
    ]
