# Generated by Django 2.2.5 on 2020-01-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0007_auto_20200112_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamseasonrecord',
            old_name='type',
            new_name='desc',
        ),
    ]
