# Generated by Django 2.2.5 on 2020-01-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0008_auto_20200112_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonrecord',
            name='teamseason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cfb.TeamSeason'),
            preserve_default=False,
        ),
    ]
