# Generated by Django 2.2.5 on 2020-01-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0009_teamseasonrecord_teamseason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamseasonrecord',
            unique_together={('desc', 'teamseason')},
        ),
    ]
