# Generated by Django 2.2.5 on 2020-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0011_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True, verbose_name='Points Scored')),
                ('oscore', models.IntegerField(null=True, verbose_name='Opponent Points Scored')),
                ('date', models.DateTimeField(null=True)),
                ('location', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('N', 'Neutral')], max_length=1, null=True, verbose_name='Game Location')),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('T', 'Tie')], max_length=1, null=True, verbose_name='Game Result')),
                ('length', models.FloatField(null=True, verbose_name='Game Length [hrs]')),
                ('attendance', models.FloatField(null=True, verbose_name='Game Attendance')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_opponent_set', to='cfb.TeamSeason')),
                ('teamseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_set', to='cfb.TeamSeason')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
