# Generated by Django 2.2.5 on 2020-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0012_auto_20200112_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='orank',
            field=models.IntegerField(null=True, verbose_name='Opponent Rank'),
        ),
    ]
