# Generated by Django 2.2.5 on 2020-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0013_gameresult_orank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='oname',
            field=models.CharField(max_length=1, null=True, verbose_name='Opponent Name'),
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('teamseason', 'opponent', 'date')},
        ),
    ]
