# Generated by Django 2.2.5 on 2020-01-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0014_auto_20200112_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_opponent_set', to='cfb.TeamSeason'),
        ),
    ]
