# Generated by Django 2.2.5 on 2020-01-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0015_auto_20200112_0809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('teamseason', 'oname', 'date')},
        ),
    ]
