# Generated by Django 2.2.5 on 2020-01-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0016_auto_20200112_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1, null=True, verbose_name='Stat Category')),
                ('desc', models.CharField(max_length=1, null=True, verbose_name='Stat Desc')),
                ('value', models.FloatField(null=True, verbose_name='Team Value')),
                ('ovalue', models.FloatField(null=True, verbose_name='Opponent Value')),
                ('teamseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfb.TeamSeason')),
            ],
            options={
                'unique_together': {('teamseason', 'category', 'desc')},
            },
        ),
    ]
