# Generated by Django 2.2.5 on 2020-01-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0018_auto_20200113_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('wiki_team_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('year_expanded', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teamseason',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfb.Stadium'),
        ),
    ]
