# Generated by Django 2.2.5 on 2020-01-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0020_stadium_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='fgr',
            field=models.FloatField(null=True, verbose_name='Federal Grad Rate'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='gsr',
            field=models.FloatField(null=True, verbose_name='Grad Success Rate'),
        ),
    ]
